--[[
| This file was obtained through the combined efforts
| of Madbluntz & Plymouth Antiquarian Society.
|
| Credits: lifestorm, Gregory Wayne Rossel JR.,
| 	Maloy, DrPepper10 @ RIP, Atle!
|
| Visit for more: https://plymouth.thetwilightzone.ru/
--]]


-- Called after all the plugins have been initialized.
function PLUGIN:InitializedPlugins()
	ix.hints.Add("Wpisz // przed wiadomością, aby napisać coś na czacie OOC.")
	ix.hints.Add("Wpisz .// lub [[ przed wiadomością, aby napisać coś na lokalnym czacie OOC.")
	ix.hints.Add("Jeśli przytrzymasz ALT i naciśniesz TAB, możesz włączyć stałe kucanie.") 
	ix.hints.Add("Naciśnij TAB, żeby otworzyć menu lub przytrzymaj TAB aby wyświetlić je tylko przez chwilę.")
	ix.hints.Add("Naciśnij E gdy patrzysz się na obiekt, aby otworzyć jego menu.")
	ix.hints.Add("Możesz zmienić opis swojej postaci używając komendy /CharDesc, menu postaci pod TAB lub w menu pod F1") 
	ix.hints.Add("Użyj komendy /CharSearch żeby przeszukać osobę, na którą się patrzysz.")
	ix.hints.Add("Przy użyciu Zip Tie, możesz zakuwać inne postacie.") 
	ix.hints.Add("Możesz dostosować niektóre ustawienia pod siebie przy użyciu opcji.")
	ix.hints.Add("Chcesz otworzyć własny Biznes? Skontaktuj się z Civil Workers Union.")
	ix.hints.Add("Serwer nie istniał by bez wsparcia społeczności. Chcesz wesprzeć go jeszcze bardziej? Rozważ zostawienie dotacji.")
	ix.hints.Add("Uważaj, aby nie utonąć podczas pływania.")
	ix.hints.Add("Twoja postać jest zwykłym człowiekiem, powstrzymaj się od skakania z dużych wysokości.")
	ix.hints.Add("Nie zapomnij żeby kiedyś pójść spać, twoja postać też się męczy..")
	ix.hints.Add("Spróbuj znaleźć sobie przyjaciół, ponoć nieszczęścia chodzą parami.")
	ix.hints.Add("Nie popełniaj przestępstwa, jeśli nie jesteś przygotowany na odsiadkę.")
	ix.hints.Add("Kombinat stale obserwuje ulice miasta. Miej to na uwadze, kiedy pomyślisz o czymś głupim.")
	ix.hints.Add("Nie działaj na własną rękę przeciwko rebelii, Kombinat pomyśli, że z nimi pracujesz.")
	ix.hints.Add("Nie zadzieraj z Kombinatem, przejęli Ziemię w 7 godzin.")
	ix.hints.Add("Masz ochotę kogoś tak po prostu uderzyć? Nawet o tym nie myśl.") 
	ix.hints.Add("Bądź posłuszny wobec władzy, nie pożałujesz.")
	ix.hints.Add("Kiedy Kombinat przyjdzie Ci z wizytą, rób co Ci każą, opór jest daremny.")
	ix.hints.Add("Potrzebujesz skontaktować się z Civil Protection? Zainwestuj w urządzenie zgłaszające.")
	ix.hints.Add("Civil Protection jest tutaj po to, żeby chronić cywilizowane społeczeństwo, nie ciebie.") 
	ix.hints.Add("Administracja jest po to, żeby Ci pomóc. Postaraj się zachować wobec niej szacunek.")
	ix.hints.Add("Staraj się nie wychodzić z postaci poprzez nieodpowiednie zachowanie, zarówno na czacie pisanym jak i na czacie głosowym.")
	ix.hints.Add("Musisz gdzieś się szybko dostać? Masz ochotę pobiegać? Zapomnij o tym, bieganie jest niecywilizowane.")
	ix.hints.Add("Kiedy znajdziesz się w strzelaninie, postaraj się czasami celowo nie trafić w swojego przeciwnika, pojedynek będzie wtedy jeszcze ciekawszy.")
	ix.hints.Add("Metagaming, czyli wykorzystywanie informacji Out-of-Character jako twoja postać, jest zabronione. Unikaj takich zachowań")
	ix.hints.Add("Pamiętaj, że grasz na serwerze roleplay. Odgrywasz swoją postać, a nie lepszą wersję samego siebie.") 
	ix.hints.Add("Dzielenie się informacjami In-Character na czacie OOC uważane jest za Metabaiting, co jest zakazane.")
	ix.hints.Add("Nic się nie dzieje i nudzi Ci się? Spróbuj pograć trochę pasywnego roleplayu.")
	ix.hints.Add("Rozwiń swoją postać, nadaj jej jakąś historię którą możesz opowiedzieć innym. Przyniesie Ci to same korzyści.")
	ix.hints.Add("Powergaming, czyli wymuszanie swojej akcji na innym graczu, jest zabronione") 
	ix.hints.Add("Kiedy zdecydujesz się użyć komendy /roll staraj się wybrać atrybut, który najbardziej pasuje do sytuacji.")
	ix.hints.Add("Większość frakcji posiada swój prywatny czat OOC. Aby zacząć na nich pisać wystarczy użyć ich inicjałów. np. /cwu")
	ix.hints.Add("Naciśnij F3 żeby przedstawić się innym postaciom wokół ciebie.")
	ix.hints.Add("Możesz ustawić sobie fałszywe imię i przedstawiać się nim, aby to zrobić, przejdź do menu postaci")
	ix.hints.Add("Nie chcesz o czymś zapomnieć? Użyj opcji 'Notatki osobiste' pod F1 i zapisz tam co chcesz.")
	ix.hints.Add("Chcesz aby twoja postać opierała się o ścianę lub wykonywała inną akcję? Możesz to zrobić używajac komendy /Act lub poprzez menu animacji pod F1.")
	ix.hints.Add("Pamiętaj aby wykorzystywać czas głosowy zgodnie z jego przeznaczeniem, inaczej zakończy się to stałym wyciszeniem lub wykluczeniem z rozgrywki.") 
	ix.hints.Add("Ktoś prosi Cię o podanie CID'u? Możesz podać go za pomocą komendy /ID.")
	ix.hints.Add("Możesz wyłączyć lub zmienić głośność muzyki w ustawieniach.")
	ix.hints.Add("Brakuje Ci miejsca? Zainwestuj w plecak albo w pojemniki, możesz w nich przechowywać przedmioty.") 
	ix.hints.Add("Potrzebujesz pomocy administracji? Opisz krótko swój problem używając @.") 
	ix.hints.Add("Ciemno? Nic nie widzisz? Kup sobie latarkę.")
	ix.hints.Add("Rozejrzyj się po przeróżnych uliczkach, zakątkach czy po śmietnikach - może znajdziesz tam coś ciekawego.")
	ix.hints.Add("Możesz łączyć różne przedmioty, żeby tworzyć z nich całkowicie nowe rzeczy, możesz to zrobić poprzez menu Wytwarzania.")
	ix.hints.Add("Większość przedmiotów może zostać rozłożona w celu uzyskania z nich surowców, możesz to zrobić poprzez menu Wytwarzania.")
	ix.hints.Add("Znudzony? Poczytaj książke. Twojej postaci przyda się trochę wiedzy.")
	ix.hints.Add("Zdobądź jakąś krótkofalówkę, żeby móc porozumiewać się z innymi na duże dystanse. Tylko uważaj, są nielegalne.")
	ix.hints.Add("Skaner próbuje zrobić Ci zdjęcie? Uśmiechnij się! Za chwilę każdy oficer CP w mieście zobaczy twoją piękną buzię.")
	ix.hints.Add("Przebywanie pod ziemią przez zbyt długi czas może skutkować wdychaniem szkodliwych gazów.")
	ix.hints.Add("Nie chcesz już podpowiedzi? Możesz wyłączyć je w opcjach.") 
	ix.hints.Add("Chcesz zmienić częstotliwość wyświetlania się podpowiedzi? Możesz zrobić to w opcjach.")
	ix.hints.Add("Coś Ci dolega? Udaj się z wizytą do Civil Medical Union. Ich usługi są darmowe!")
	ix.hints.Add("Możesz oddać krew do Civil Medical Union, w zamian możesz otrzymać kupon na Kredyty Społeczne.")
	ix.hints.Add("Jeśli masz jakąś propozycje odnośnie rozgrywki - napisz ją na discordzie serwera.")
	ix.hints.Add("Utknąłeś w ścianie? Użyj komendy /UnStuck! Uwaga, nadużywanie tej komendy może spotkać się z karą.")
	ix.hints.Add("Możesz dostosować ustawienia immersyjności poprzez opcje.")
end
